/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "ybbixkyyzjihwxklvvsw"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InliYml4a3l5emppaHd4a2x2dnN3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM1Mjk1MDgsImV4cCI6MjA2OTEwNTUwOH0.jtD9GKvcAd--qC7KqQ2R35Rxbj0INi1K1AMwbixGa7c"